### ISSUE TITLE
Port to .NET Core

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Nancy.Serilog#3]
Preferably by linking the same source files into a netstandard2.0 based project and building/publishing from there

**Comment by Jaxelr** [comment]
Is the plan also to allow to target Nancy 2.X?

**Comment by Zaid-Ajaj** [comment]
Hi @Jaxelr 
Yes, netstandard2.0 support is mainly to support Nancy 2.x. I will probably make a seperate package for it because this package doesn’t work out of the box for 2.0-clinteastwood.

**Comment by Zaid-Ajaj** [comment]
@Jaxelr .NET Core version is published: `Nancy.Serilog.Core`, see README.md there is also a CoreSample in the repo using it :smile:

**Comment by Jaxelr** [comment]
Thanks!
